### ISSUE TITLE
Add support for partial permutation streams

### ISSUE THREAD

**Issue by siordache** [beryx/streamplify#3]
This is an _up-for-grabs_ issue, so hurry up and grab it!

Your task is to add support for [partial permutation](https://en.wikipedia.org/wiki/Partial_permutation) streams.
(Note that the term _partial permutation_ is sometimes used to denote [k-permutations of n](https://en.wikipedia.org/wiki/Permutation#k-permutations_of_n). This issue is NOT about this kind of permutations.)

Consult the implementation of the other combinatorics classes (permutations, combinations, Cartesian product) and structure your code in a similar way:
- put your classes in a package named `org.beryx.streamplify.partperm`.
- create a subclass of [LongIndexedSpliterator](../blob/master/streamplify/src/main/java/org/beryx/streamplify/LongIndexedSpliterator.java)  called `LongPartialPermutations`, which can be used for partial permutations with a cardinality that fits in a long (that is, for sets with at most 20 elements).
  _Hint_: use [LongPermutations.java](../blob/master/streamplify/src/main/java/org/beryx/streamplify/permutation/LongPermutations.java) as template for this class.
- create a subclass of [BigIntegerIndexedSpliterator](../blob/master/streamplify/src/main/java/org/beryx/streamplify/BigIntegerIndexedSpliterator.java) called `BigIntegerPartialPermutations`, which allows partial permutations of virtually any cardinality.
  _Hint_: use [BigIntegerPermutations.java](../blob/master/streamplify/src/main/java/org/beryx/streamplify/permutation/BigIntegerPermutations.java) as template for this class.
- create a [StreamableProxy](../blob/master/streamplify/src/main/java/org/beryx/streamplify/StreamableProxy.java)  called`PartialPermutations`, which delegates to either _LongPartialPermutations_ or _BigIntegerPartialPermutations_.
  _Hint_: use [Permutations.java](../blob/master/streamplify/src/main/java/org/beryx/streamplify/permutation/Permutations.java) as template for this class.
- create an abstract class called `PartialPermutationSupplier`, which implements [IntArraySupplier](../blob/master/streamplify/src/main/java/org/beryx/streamplify/IntArraySupplier.java) and has two concrete subclasses: the static nested classes `Long` and `BigInteger`.
  The `int[]`representation of a partial permutation should use `-1` for the holes.
  _Hint_: use [PermutationSupplier.java](../blob/master/streamplify/src/main/java/org/beryx/streamplify/permutation/PermutationSupplier.java) as template for this class.
  (This is the most challenging class to be implemented, because you have to come up with efficient algorithms for the methods _computeNext()_ and _unrank()_.)

Your pull request should also contain:
- [Spock](http://spockframework.org/) unit tests - see for example [PermutationsSpec.groovy](../blob/master/streamplify/src/test/groovy/org/beryx/streamplify/PermutationsSpec.groovy)
- examples - should be placed in [streamplify-examples](../blob/master/streamplify-examples/src/main/java/org/beryx/streamplify/example)
- documentation (using [Asciidoctor](http://asciidoctor.org/))

In order to prevent that two people work on the same thing, leave a comment here to claim this issue before starting to work on it.

Happy coding, and don't hesitate to ask for clarification and guidance.

**Comment by MattRake** [comment]
Hi, I would like to claim this issue :smiley:

**Comment by siordache** [comment]
It's yours. Have fun!

**Comment by MattRake** [comment]
@siordache  I have a few issues I'm unsure about. 

Following wiki notation on [partial permutations](https://en.wikipedia.org/wiki/Partial_permutation) we need some identifier for the "hole" element. For example when enumerating partial permutations of length 2, we need to be able not only to return array `[1,2], [2,1]`but also `[1,x]` and `[x,x], [x,2],[2,x],[x,1]`, where `x` represents a special hole element. 

Could I use some negative integer, for example -1 to represent that special element? Or should I create wrapper class on integers which could also describe hole element, and then enumerate over arrays of these wrapper objects `Wrapper[] arrays` instead of`int[] arrays`? Idea of wrapper seems a lit bit more sound to me, but I saw that in other classes we use straight `int[]` arrays for combinatoric objects and I feel it would not be good to break this convention.

I have one more question, just for confirmation. When speaking of  partial permutation we want to iterate over **all** of them, so as wiki says for `n=2` we want to generate seven partial permutations? My second thought was that maybe we want to add other parameter `k` which would describe how many holes we want in partial permutations, so for `length n = 2, k =1`  there would be four results`[1,x], [2,x], [x,1], [x,2]`. Note that would be something else than [k-permutation](https://en.wikipedia.org/wiki/Permutation#k-permutations_of_n).

Regards!

**Comment by siordache** [comment]
@MattRake 
1. I favor the idea of sticking with int[] and using -1 to represent the holes. Users can subsequently map the elements of a partial permutation stream to a wrapper class or any other representation they wish.
2. Yes, we want to iterate over **all** of them.  But if it turns out that it is too difficult to come up with algorithms for _computeNext()_ and _unrank()_ for this global case, a solution with an additional parameter for the number of holes is also ok.

Regards!

**Comment by siordache** [comment]
@MattRake How is this going? Do you need any help?

**Comment by siordache** [comment]
The issue is _up-for-grabs_ again.

**Comment by johnhadfield** [comment]
Hi, this looks like a fun problem! Can I give it a shot? I have a few ideas for the _computeNext()_ and _unrank()_ methods.

**Comment by siordache** [comment]
Grabbed by @johnhadfield 

Have fun!

**Comment by siordache** [comment]
Implemented in #6 by @johnhadfield 

Will be released in 1.1.0.
